swagger: "2.0"
info:
  description: "API to operate an IoT lock from Smart Azure Systems!"
  version: "0.1.0"
  title: "IoT Lock"
  contact:
    email: "rezas@microsoft.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "lock.shkreza.com:4443"
host: "lock.endpoints.iot-api-gateway.cloud.goog"
x-google-endpoints: [
  {
    name: "lock.endpoints.iot-api-gateway.cloud.goog",
    allowCors: true
  }
]
basePath: "/api/v0"
tags:
- name: "lock"
  description: "Something that you can lock or unlock"
  externalDocs:
    description: "Find out more"
    url: "https://lock.shkreza.com"
- name: "capture"
  description: "Captures an image"
  externalDocs:
    description: "Find out more"
    url: "https://lock.shkreza.com"
schemes:
- "https"
paths:
  /lock:
    post:
      tags:
      - "lock"
      summary: "Lock the lock"
      description: "Lock the lock"
      operationId: "lock_post"
      parameters:
      - $ref: "#/parameters/iothub-deviceid"
      - $ref: "#/parameters/iothub-hubname"
      responses:
        501:
          description: "Not Implemented"
      security:
      - firebase: []
    get:
      tags:
      - "lock"
      summary: "Lock the lock"
      description: "Lock the lock"
      operationId: "lock_get"
      parameters:
      - $ref: "#/parameters/iothub-deviceid"
      - $ref: "#/parameters/iothub-hubname"
      responses:
        501:
          description: "Not Implemented"
      security:
      - firebase: []
  /lock/capture:
    get:
      tags:
      - "lock"
      - "capture"
      summary: "Capture image of the lock"
      description: "Capture image of the lock"
      operationId: "lock_capture_get"
      parameters:
      - $ref: "#/parameters/iothub-deviceid"
      - $ref: "#/parameters/iothub-hubname"
      responses:
        501:
          description: "Not Implemented"
      security:
      - firebase: []
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # Replace YOUR-PROJECT-ID with your project ID
    x-google-issuer: "https://securetoken.google.com/iot-api-gateway"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    x-google-audiences: "iot-api-gateway"
parameters:
  iothub-deviceid:
    in: header
    name: x-device-id
    description: Device ID in IoT Hub
    required: true
    type: string
  iothub-hubname:
    in: header
    name: x-hub-name
    description: IoT Hub name
    required: true
    type: string
