kind: Service
apiVersion: v1
metadata:
    name: lock-backend
spec:
    selector:
        app: lock-backend
    ports:
    - name: port-4443
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port-443
      protocol: TCP
      port: 443
      targetPort: 443
    type:
        LoadBalancer
